# contains instructions to run the app locally
version: "2"
services:
  db:
    image: postgres
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      # mounting each volume separately so as not to mask the fs in container
      - "./views:/usr/src/app/views"
      - "./db:/usr/src/app/db"
      - "./public:/usr/src/app/public"
      - "./app.js:/usr/src/app/app.js"
      - "./routes:/usr/src/app/routes"
    entrypoint:
      - "npm"
      - "start"

